### ISSUE TITLE
Not working on aspnetcore 1.1

### ISSUE THREAD

**Issue by thiagottss** [fujiy/Fujiy.ApplicationInsights.AspNetCore.SqlTrack#2]
It supposed to work with Microsoft.ApplicationInsights.AspNetCore (2.1.1) package?
https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/ 

I saw on Nuget that you are using Microsoft.ApplicationInsights and not aspnetcore.
https://www.nuget.org/packages/Fujiy.ApplicationInsights.AspNetCore.SqlTrack/

**Comment by felipepessoto** [comment]
Actually it is not working with EF Core 2
